# Generated by Django 3.0.6 on 2020-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads/docs'),
        ),
        migrations.AlterField(
            model_name='document',
            name='note_soutenance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
