# Generated by Django 3.0.6 on 2020-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200607_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ('nom_complet',)},
        ),
        migrations.AlterField(
            model_name='document',
            name='date_selection',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Selection'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_soutenance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Soutenance'),
        ),
        migrations.AlterField(
            model_name='document',
            name='etablissement',
            field=models.CharField(choices=[('FSJP', 'Faculté des Sciences Juridiques et Politiques'), ('FSEG', 'Faculté des Sciences Economiques et de Gestion')], default='FSEG', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('MAS', 'Mémoire de Master'), ('DOC', 'Thèse de Doctorat')], default='MAS', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_formation',
            field=models.CharField(choices=[('ACC', 'Formation Académique'), ('PRO', 'Formation professionnelle')], default='ACC', max_length=3, null=True),
        ),
    ]
