# Generated by Django 2.1.3 on 2020-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='role_enseignant',
            field=models.CharField(choices=[('JUR', 'Membre du Jury'), ('ENC', 'Encadreur')], max_length=3),
        ),
    ]
