# Generated by Django 3.0.6 on 2020-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='note_soutenance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Date de Publication '),
        ),
    ]
