# Generated by Django 3.0.6 on 2020-06-16 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200612_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 9, 1, 49, 576232, tzinfo=utc), null=True, verbose_name='Date de Publication '),
        ),
    ]
