# Generated by Django 3.0.6 on 2020-06-16 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200616_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 9, 2, 43, 591115, tzinfo=utc), null=True, verbose_name='Date de Publication '),
        ),
    ]
